# Generated by Django 3.2.4 on 2021-06-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('risco', models.IntegerField()),
                ('participantes', models.CharField(max_length=255)),
            ],
        ),
    ]
